### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by namoshizun** [namoshizun/TradePy#26]

**Comment by lovetimil** [comment]
需要文档，能麻烦优先提供使用文档，部署文档。可以让用户先跑起来的说明。
跑起来后，程序员可以调试，看代码就方便了。

**Comment by namoshizun** [comment]
> 

开始写文档了，在doc分支

**Comment by namoshizun** [comment]
> 需要文档，能麻烦优先提供使用文档，部署文档。可以让用户先跑起来的说明。 跑起来后，程序员可以调试，看代码就方便了。


开始写文档了，在doc分支
