### ISSUE TITLE
Can TradePy be depoyed on mac OS ?

### ISSUE THREAD

**Issue by odoofans** [namoshizun/TradePy#36]

**Comment by namoshizun** [comment]
Hmmm I assume by deployment you mean to use TradePy for live / paper trading with QMT. The strategy execution end can be deployed on any unix-like system, including macOS. But for the trading end where the QMT is run, it has to be Windows because QMT doesn't support other operating systems.

**Comment by odoofans** [comment]
OK, I will try to deploy the strategy execution end on mac OS.
