### ISSUE TITLE
执行 update_data_source 时发生错误，推送异常 NO Such file or directory "listing.csv"

### ISSUE THREAD

**Issue by odoofans** [namoshizun/TradePy#38]

**Comment by odoofans** [comment]
股票列表需要手工更新吗？

**Comment by namoshizun** [comment]
是的，需要先下载股票列表以及复权因子，具体方式请看”快速上手“教程。 在实盘教程中由于假设这一步已经完成了，就没有加上去。 不过的确如果实盘策略端的服务器是新购的话，比较容易遗漏这一步。 我准备将下载基础数据加入到 tradepy.cli.bootstrap 中，以防遗漏。

**Comment by odoofans** [comment]
执行 StocksListingCollector().run(batch_size=25) 下载股票列表后问题解决。复权因子可以自动更新。
