### ISSUE TITLE
过了交易时间段，比如下午16:08， fetch_market_quote 还在运行？

### ISSUE THREAD

**Issue by odoofans** [namoshizun/TradePy#40]

**Comment by namoshizun** [comment]
是的，但也仅仅是被触发而已，交易时间段以外不会实际地去拉取行情或触发交易。它持续被触发的原因，是因为Celery beat schedule目前的scheduling机制还不太完善，无法直接定义"9:15到15:00之间，每n秒触发一次任务"。
