### ISSUE TITLE
Support mock trading？

### ISSUE THREAD

**Issue by eromoe** [namoshizun/TradePy#47]
Hi, this is a pretty good project. 
As I am plan to do live trading, would like to run a strategy in simulation way.
Do you have a plan?

**Comment by namoshizun** [comment]
Yep that's fully supported. In fact, there is little difference between the live trading and paper-trading in this framework. You may simply change the `mode` in the configuration to `paper-trading` to get started, as mentioned in the [doc](https://docs.trade-py.com/trading.html#id6). 

To ensure we are on the same page -- it is the QMT that handles order processing and account management, so you will need to install 2 QMTs on your windows server, one for live trading and the other for paper trading

**Comment by eromoe** [comment]
That's very nice ! 
A little confused about the 2 QMTs, 
1. Since simulation doesn't need perfrom buy/sell actually, why need QMT ?
2. Or do you mean deploy two TradePy servers ?

**Comment by namoshizun** [comment]
Hmmmm I am not sure whether we are fully synced on the terminologies here 😂 In the general sense, there are 3 modes:

- `backtest`: No QMT involved, just re-playing the history stock data and apply a strategy to decide buying & selling (is this the "simulation" you talked about?)
- `live-trading`: Need QMT to receive orders. The doc has a section for guidance on how to set up a live trading environment.
- `paper-trading`: 99% like the live trading, except that the QMT client you are running should be one that supports the paper-trading / mock-trading, i.e., it still process orders as if it is the live-trading, but using your paper-trading account.

You should have two QMT accounts and client side software, one for live trading and the other for paper trading.

**Comment by eromoe** [comment]
Oh, I undertood. Since I didn't seen QMT client have paper-trading / mock-trading .. thanks for instruction.

By the way, how do you deploy QMT on Mac ? I tried Parallels Desktop with Win 11 ARM version,  not able to install QMT client ..

**Comment by namoshizun** [comment]
Ah I haven't tried deploying QMT on Mac before 👀 not sure whether QMT actually supports the ARM platform...

**Comment by eromoe** [comment]
Yeah maybe Arm is the problem, my securities manager say that they can detect virtual machines though I don't beleve it😂
