### ISSUE TITLE
运行代码时遇到的一个问题

### ISSUE THREAD

**Issue by codelyc** [namoshizun/TradePy#51]
![image](https://github.com/namoshizun/TradePy/assets/39026016/77f951d8-84bb-4600-87aa-4705918b6bc3)
import OptimizationScheduler 的时候会报错
![image](https://github.com/namoshizun/TradePy/assets/39026016/c8c73664-daca-4e85-99f0-ffad3aa3e3f5)
原因是cls.model_fields 没有 你yaml配置文件中对应的配置key字段。例如 config字段，报错信息如下
![image](https://github.com/namoshizun/TradePy/assets/39026016/eebc15d2-c400-4b49-a4bf-504e6488c79e)

**Comment by codelyc** [comment]
![image](https://github.com/namoshizun/TradePy/assets/39026016/f77c5537-c044-48da-8759-10ea521c6bdd)
![image](https://github.com/namoshizun/TradePy/assets/39026016/47375741-45a9-43d4-9aff-042ab2c01678)
解析yaml的时候，应该对yaml解析出的dict 的value 进行获取配置参数吧

**Comment by namoshizun** [comment]
请按照文档步骤来初始化tradepy config yaml，你用的这个config是给tradepy.cli.optimize脚本使用的。
